on:
  schedule:
    - cron: '5 13 * * *'
  workflow_dispatch:
    branches: [main]

jobs:
  render:
    name: nowcasting
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install dependencies
        run: |
          R_LIBS_USER="${{ github.workspace }}/R/library"
          mkdir -p "${R_LIBS_USER}"
          Rscript -e 'install.packages(c("remotes", "pkgload", "pak", "writexl","httr", "jsonlite", "dplyr","qdapRegex","xlsx","devtools","telegram.bot"), lib = "${R_LIBS_USER}")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE, lib = "${R_LIBS_USER}")'
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Execute Script
        run: |
          Rscript "inst/rodar_esus.R"
      - name: Commit and Push
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add inst/nowcast.RData
          git commit -F mensagem-comit.txt || echo "No changes to commit"
          git push origin || echo "No changes to commit"
